# Generated by Django 4.2.28 on 2026-02-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/%Y/%m/%d/')),
                ('job_description', models.TextField()),
                ('similarity_score', models.FloatField(default=0.0)),
                ('match_percentage', models.FloatField(default=0.0)),
                ('resume_skills', models.JSONField(blank=True, default=list)),
                ('job_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
